const LANGUAGE = {
  "en-US": {
    gptMovieSearch: "GPT Movie Search",
    gptSearch: "GPT Search",
    Search: "Search",
    searchMoviesUsingGPT: "Search movies using GPT...",
    popularMovies: "Popular Movies",
    topRatedMovies: "Top Rated Movies",
    trendingMovies: "Trending Movies",
    play: "Play",
    moreInfo: "More Info",
  },
  "hi-IN": {
    gptMovieSearch: "GPT मूवी खोज",
    gptSearch: "GPT खोज",
    Search: "खोजें",
    searchMoviesUsingGPT: "GPT का उपयोग करके मूवी खोजें...",
    popularMovies: "लोकप्रिय फिल्में",
    topRatedMovies: "शीर्ष रेटेड फिल्में",
    trendingMovies: "प्रचलित फिल्में",
    play: "चलाएं",
    moreInfo: "अधिक जानकारी",
  },
  "te-IN": {
    gptMovieSearch: "GPT మూవీ శోధన",
    gptSearch: "GPT శోధన",
    Search: "శోధించండి",
    searchMoviesUsingGPT: "GPT ఉపయోగించి సినిమాలు శోధించండి...",
    popularMovies: "ప్రసిద్ధ సినిమాలు",
    topRatedMovies: "అత్యున్నత రేటింగ్ సినిమాలు",
    trendingMovies: "ట్రెండింగ్ సినిమాలు",
    play: "ప్లే చేయండి",
    moreInfo: "మరింత సమాచారం",
  },
  "es-ES": {
    gptMovieSearch: "Búsqueda de películas GPT",
    gptSearch: "Búsqueda GPT",
    Search: "Buscar",
    searchMoviesUsingGPT: "GPT películas usando GPT...",
    popularMovies: "Películas populares",
    topRatedMovies: "Películas mejor calificadas",
    trendingMovies: "Películas de tendencia",
    play: "Reproducir",
    moreInfo: "Más información",
  },
};
export default LANGUAGE;
